# .github/workflows/ci.yml
name: C CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # ─── HERE ─── install everything we need ──────────────
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      # ──────────────────────────────────────────────────────
      - name: Build & run all demos+tests
        working-directory: .
        run: make check