# .github/workflows/ci.yml
name: C CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # install gcc, make, etc if you need it (on ubuntu-latest it's already there)
      - name: Build & run all demos+tests
        working-directory: .
        run: make check